DROP TABLE `analyticsSnapshots`;--> statement-breakpoint
DROP TABLE `apiKeyLogs`;--> statement-breakpoint
DROP TABLE `apiKeys`;--> statement-breakpoint
DROP TABLE `auditLogs`;--> statement-breakpoint
DROP TABLE `batchUploadFiles`;--> statement-breakpoint
DROP TABLE `batchUploads`;--> statement-breakpoint
DROP TABLE `boutiqueBankAccounts`;--> statement-breakpoint
DROP TABLE `boutiqueCredits`;--> statement-breakpoint
DROP TABLE `boutiqueSettings`;--> statement-breakpoint
DROP TABLE `boutiqueTransactions`;--> statement-breakpoint
DROP TABLE `boutiqueUsers`;--> statement-breakpoint
DROP TABLE `boutiques`;--> statement-breakpoint
DROP TABLE `deletionLogs`;--> statement-breakpoint
DROP TABLE `emailNotifications`;--> statement-breakpoint
DROP TABLE `favorites`;--> statement-breakpoint
DROP TABLE `garments`;--> statement-breakpoint
DROP TABLE `paymentReconciliation`;--> statement-breakpoint
DROP TABLE `payoutAuditLog`;--> statement-breakpoint
DROP TABLE `payoutTransactions`;--> statement-breakpoint
DROP TABLE `payouts`;--> statement-breakpoint
DROP TABLE `productSizeVariants`;--> statement-breakpoint
DROP TABLE `products`;--> statement-breakpoint
DROP TABLE `reviews`;--> statement-breakpoint
DROP TABLE `shopOrders`;--> statement-breakpoint
DROP TABLE `transactions`;--> statement-breakpoint
DROP TABLE `tryOnAnalytics`;--> statement-breakpoint
DROP TABLE `tryOnResults`;--> statement-breakpoint
DROP TABLE `userCredits`;--> statement-breakpoint
DROP TABLE `users`;--> statement-breakpoint
DROP TABLE `webhookAlerts`;--> statement-breakpoint
DROP TABLE `webhookEvents`;--> statement-breakpoint
DROP TABLE `widgetAnalytics`;--> statement-breakpoint
DROP TABLE `widgets`;