import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { BarChart3, Download, TrendingUp } from "lucide-react";
import { useState } from "react";

export function ROICalculator() {
  const [monthlyOrders, setMonthlyOrders] = useState(1000);
  const [currentReturnRate, setCurrentReturnRate] = useState(35);
  const [avgOrderValue, setAvgOrderValue] = useState(500);
  const [tryOnAdoptionRate, setTryOnAdoptionRate] = useState(60);

  // Constants
  const FITROOM_COST_PER_TRYON = 0.035; // ZAR
  const STYLESWAP_PRICE_PER_TRYON = 0.05; // ZAR (your price)
  const PROFIT_PER_TRYON = STYLESWAP_PRICE_PER_TRYON - FITROOM_COST_PER_TRYON;
  const RETURN_LOGISTICS_COST = 50; // ZAR per return
  const NEW_RETURN_RATE = currentReturnRate * 0.7; // 30% reduction

  // Calculations
  const monthlyTryOns = Math.round((monthlyOrders * tryOnAdoptionRate) / 100);
  const currentMonthlyReturns = Math.round((monthlyOrders * currentReturnRate) / 100);
  const newMonthlyReturns = Math.round((monthlyOrders * NEW_RETURN_RATE) / 100);
  const returnsReduced = currentMonthlyReturns - newMonthlyReturns;

  const monthlyTryOnRevenue = monthlyTryOns * PROFIT_PER_TRYON;
  const monthlyReturnSavings = returnsReduced * RETURN_LOGISTICS_COST;
  const totalMonthlyBenefit = monthlyTryOnRevenue + monthlyReturnSavings;

  const annualBenefit = totalMonthlyBenefit * 12;
  const annualTryOnRevenue = monthlyTryOnRevenue * 12;
  const annualReturnSavings = monthlyReturnSavings * 12;

  // ROI Calculation (assuming setup cost of R5000)
  const setupCost = 5000;
  const roi = ((annualBenefit - setupCost) / setupCost) * 100;
  const paybackMonths = Math.ceil(setupCost / totalMonthlyBenefit);

  const handleDownloadReport = () => {
    const report = `
StyleSwap ROI Calculator Report
================================

Input Parameters:
- Monthly Orders: ${monthlyOrders.toLocaleString()}
- Current Return Rate: ${currentReturnRate}%
- Average Order Value: R${avgOrderValue.toLocaleString()}
- Try-On Adoption Rate: ${tryOnAdoptionRate}%

Monthly Metrics:
- Virtual Try-Ons: ${monthlyTryOns.toLocaleString()}
- Current Returns: ${currentMonthlyReturns.toLocaleString()}
- Projected Returns: ${newMonthlyReturns.toLocaleString()}
- Returns Reduced: ${returnsReduced.toLocaleString()}

Monthly Financial Impact:
- Try-On Revenue: R${monthlyTryOnRevenue.toLocaleString()}
- Return Logistics Savings: R${monthlyReturnSavings.toLocaleString()}
- Total Monthly Benefit: R${totalMonthlyBenefit.toLocaleString()}

Annual Financial Impact:
- Annual Try-On Revenue: R${annualTryOnRevenue.toLocaleString()}
- Annual Return Savings: R${annualReturnSavings.toLocaleString()}
- Total Annual Benefit: R${annualBenefit.toLocaleString()}

ROI Analysis:
- Setup Cost: R${setupCost.toLocaleString()}
- Annual ROI: ${roi.toLocaleString()}%
- Payback Period: ${paybackMonths} months

Generated by StyleSwap ROI Calculator
    `;
    
    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(report));
    element.setAttribute('download', 'styleswap-roi-report.txt');
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <section className="py-20 container mx-auto">
      <div className="text-center mb-16">
        <h2 className="text-5xl md:text-6xl font-bold mb-6">ROI CALCULATOR</h2>
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
          Discover your potential earnings and savings by implementing StyleSwap. All calculations in South African Rands.
        </p>
      </div>

      <div className="grid lg:grid-cols-2 gap-12">
        {/* Input Section */}
        <Card className="premium-card rounded-2xl">
          <CardHeader>
            <CardTitle>Your Business Parameters</CardTitle>
          </CardHeader>
          <CardContent className="space-y-8">
            {/* Monthly Orders */}
            <div>
              <label className="block text-sm font-bold mb-3">
                Monthly Orders: <span className="text-primary">{monthlyOrders.toLocaleString()}</span>
              </label>
              <input
                type="range"
                min="100"
                max="10000"
                step="100"
                value={monthlyOrders}
                onChange={(e) => setMonthlyOrders(Number(e.target.value))}
                className="w-full h-2 bg-secondary/30 rounded-lg appearance-none cursor-pointer accent-primary"
              />
              <div className="flex justify-between text-xs text-muted-foreground mt-2">
                <span>100</span>
                <span>10,000</span>
              </div>
            </div>

            {/* Current Return Rate */}
            <div>
              <label className="block text-sm font-bold mb-3">
                Current Return Rate: <span className="text-primary">{currentReturnRate}%</span>
              </label>
              <input
                type="range"
                min="10"
                max="50"
                step="1"
                value={currentReturnRate}
                onChange={(e) => setCurrentReturnRate(Number(e.target.value))}
                className="w-full h-2 bg-secondary/30 rounded-lg appearance-none cursor-pointer accent-primary"
              />
              <div className="flex justify-between text-xs text-muted-foreground mt-2">
                <span>10%</span>
                <span>50%</span>
              </div>
            </div>

            {/* Average Order Value */}
            <div>
              <label className="block text-sm font-bold mb-3">
                Average Order Value: <span className="text-primary">R{avgOrderValue.toLocaleString()}</span>
              </label>
              <input
                type="range"
                min="100"
                max="2000"
                step="50"
                value={avgOrderValue}
                onChange={(e) => setAvgOrderValue(Number(e.target.value))}
                className="w-full h-2 bg-secondary/30 rounded-lg appearance-none cursor-pointer accent-primary"
              />
              <div className="flex justify-between text-xs text-muted-foreground mt-2">
                <span>R100</span>
                <span>R2,000</span>
              </div>
            </div>

            {/* Try-On Adoption Rate */}
            <div>
              <label className="block text-sm font-bold mb-3">
                Try-On Adoption Rate: <span className="text-primary">{tryOnAdoptionRate}%</span>
              </label>
              <input
                type="range"
                min="10"
                max="100"
                step="5"
                value={tryOnAdoptionRate}
                onChange={(e) => setTryOnAdoptionRate(Number(e.target.value))}
                className="w-full h-2 bg-secondary/30 rounded-lg appearance-none cursor-pointer accent-primary"
              />
              <div className="flex justify-between text-xs text-muted-foreground mt-2">
                <span>10%</span>
                <span>100%</span>
              </div>
              <p className="text-xs text-muted-foreground mt-3">
                Percentage of customers who use virtual try-on feature
              </p>
            </div>

            <Button 
              onClick={handleDownloadReport}
              className="w-full premium-button bg-secondary text-secondary-foreground hover:bg-secondary/90 h-12 font-bold"
            >
              <Download className="w-4 h-4 mr-2" />
              Download Report
            </Button>
          </CardContent>
        </Card>

        {/* Results Section */}
        <div className="space-y-6">
          {/* Monthly Metrics */}
          <Card className="premium-card rounded-2xl bg-gradient-to-br from-primary/10 to-secondary/10 border-primary/30">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BarChart3 className="w-5 h-5 text-primary" />
                Monthly Impact
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="p-4 bg-background rounded-lg border border-border/20">
                  <div className="text-xs text-muted-foreground mb-1">Virtual Try-Ons</div>
                  <div className="text-2xl font-bold text-primary">{monthlyTryOns.toLocaleString()}</div>
                </div>
                <div className="p-4 bg-background rounded-lg border border-border/20">
                  <div className="text-xs text-muted-foreground mb-1">Returns Reduced</div>
                  <div className="text-2xl font-bold text-primary">{returnsReduced.toLocaleString()}</div>
                </div>
              </div>
              <div className="p-4 bg-background rounded-lg border border-border/20">
                <div className="text-xs text-muted-foreground mb-1">Try-On Revenue</div>
                <div className="text-2xl font-bold text-primary">R{monthlyTryOnRevenue.toLocaleString()}</div>
              </div>
              <div className="p-4 bg-background rounded-lg border border-border/20">
                <div className="text-xs text-muted-foreground mb-1">Return Logistics Savings</div>
                <div className="text-2xl font-bold text-primary">R{monthlyReturnSavings.toLocaleString()}</div>
              </div>
              <div className="p-4 bg-primary/20 rounded-lg border border-primary/30">
                <div className="text-xs text-muted-foreground mb-1">Total Monthly Benefit</div>
                <div className="text-3xl font-bold text-primary">R{totalMonthlyBenefit.toLocaleString()}</div>
              </div>
            </CardContent>
          </Card>

          {/* Annual ROI */}
          <Card className="premium-card rounded-2xl bg-gradient-to-br from-secondary/10 to-primary/10 border-secondary/30">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-secondary" />
                Annual ROI
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="p-4 bg-background rounded-lg border border-border/20">
                <div className="text-xs text-muted-foreground mb-1">Annual Try-On Revenue</div>
                <div className="text-2xl font-bold text-secondary">R{annualTryOnRevenue.toLocaleString()}</div>
              </div>
              <div className="p-4 bg-background rounded-lg border border-border/20">
                <div className="text-xs text-muted-foreground mb-1">Annual Return Savings</div>
                <div className="text-2xl font-bold text-secondary">R{annualReturnSavings.toLocaleString()}</div>
              </div>
              <div className="p-4 bg-secondary/20 rounded-lg border border-secondary/30">
                <div className="text-xs text-muted-foreground mb-1">Total Annual Benefit</div>
                <div className="text-3xl font-bold text-secondary">R{annualBenefit.toLocaleString()}</div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="p-4 bg-background rounded-lg border border-border/20 text-center">
                  <div className="text-xs text-muted-foreground mb-1">ROI</div>
                  <div className="text-2xl font-bold text-secondary">{roi.toLocaleString()}%</div>
                </div>
                <div className="p-4 bg-background rounded-lg border border-border/20 text-center">
                  <div className="text-xs text-muted-foreground mb-1">Payback Period</div>
                  <div className="text-2xl font-bold text-secondary">{paybackMonths} months</div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  );
}
